#!/usr/bin/python
#Can supply a single bed gzip
#
#Supply an option for tab or not
#Output filename autogenerated based on input file name
#Output file directory must be specified
#
#For the bed gzip
#Will filter out into the different chromosomes temp files
#Will call bedtools
#Will concatenate the temp files
#
#We also need something that accepts a function that generates the command to execute, and then executes on all files in the
#directory that satisfy a certain boolean condition I guess.
#

import sys;
import gzip;

if (len(sys.argv) < 2):
	print "Please supply the bed file as the first argument";
	sys.exit(0);

inputBedFile = sys.argv[1];





