apiVersion: v1 
kind: PersistentVolumeClaim
metadata:                                                                       
    name: pvc1rwx 
spec:                                                                           
    storageClassName: rook-block
    accessModes:
    - ReadWriteMany 
    resources:
        requests:
            storage: 275Gi
