apiVersion: v1
kind: Pod
metadata:
    name: cpupod1-genomics
spec:
    containers:
    - name: container1-tfgenomics
      image: dskim89/tensorflow-genomics
      args: ["sleep", "infinity"]
      resources:
          limits:
              cpu: 40
              memory: 60Gi
          requests:
              cpu: 12
              memory: 30Gi
      volumeMounts:
      - mountPath: /data
        name: pvc1rwx
    restartPolicy: Never
    volumes:
    - name: pvc1rwx
      persistentVolumeClaim:
        claimName: pvc1rwx
