apiVersion: v1
kind: Pod
metadata:
    name: gpupod1-tfgenomics
spec:
    containers:
    - name: container1-tfgenomics
      image: dskim89/tensorflow-genomics
      args: ["sleep", "infinity"]
      resources:
          limits:
              nvidia.com/gpu: 1
              cpu: 40
              memory: 30Gi
          requests:
              cpu: 12
              memory: 12Gi
      volumeMounts:
      - mountPath: /data
        name: cephblock1
    restartPolicy: Never
    volumes:
    - name: cephblock1
      flexVolume:
        driver: ceph.rook.io/rook
        fsType: ceph
        options:
          fsName: nautilusfs
          clusterNamespace: rook
          path: /av
