apiVersion: v1
kind: Pod
metadata:
    name: gpupod1-tfgenomics
spec:
    containers:
    - name: container1-tfgenomics
      image: dskim89/tensorflow-genomics
      args: ["sleep", "infinity"]
      resources:
          limits:
              nvidia.com/gpu: 1
              cpu: 40
              memory: 30Gi
          requests:
              cpu: 12
              memory: 12Gi
      volumeMounts:
      - mountPath: /data
        name: pvc1rwx
    restartPolicy: Never
    volumes:
    - name: pvc1rwx
      persistentVolumeClaim:
        claimName: pvc1rwx
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
              - key: gpu-type
                operator: In # Use NotIn for other types
                values:
                - "1080Ti"
